require 'net/http'

class Match < ActiveRecord::Base
  belongs_to :a, :class_name => "User", :foreign_key => :a_id
  belongs_to :b, :class_name => "User", :foreign_key => :b_id

  def email!
    API_KEY = ENV['MAILGUN_API_KEY']
    MAIL_DOMAIN = ENV['MAIL_DOMAIN']

    if !API_KEY
      raise "API_KEY is not set in ENV."
    end

    if !MAIL_DOMAIN
      raise "MAIL_DOMAIN is not set in ENV."
    end

    API_URL = URI("https://api:#{API_KEY}@api.mailgun.net/v2/#{MAIL_DOMAIN}")

    res = Net::HTTP.post_form(
      API_URL,
      :from => "noreply@#{MAIL_DOMAIN}",
      :to => [a.email, b.email].join(','),
      :subject => "Recurser, you've been matched!",
      :text => email_body,
    )

    def email_body
        return <<-BODY

        Hello!

        You two should meet:

        #{a.name} - #{a.email}

        #{b.name} - #{b.email}

        This is an autogenerated email by https://meetrc.herokuapp.com. It is an opt-in way to meet fellow recursers. We heartily suggest you respond to this email and set up a time and place to hang out!

        <3s
        Doorbot.

        BODY
    end
  end
end
