require 'net/http'

API_KEY = ENV['MAILGUN_API_KEY']
MAIL_DOMAIN = ENV['MAIL_DOMAIN']

class Match < ActiveRecord::Base
  belongs_to :a, :class_name => "User", :foreign_key => :a_id
  belongs_to :b, :class_name => "User", :foreign_key => :b_id

  def email!
    if !API_KEY
      raise "API_KEY is not set in ENV."
    end

    if !MAIL_DOMAIN
      raise "MAIL_DOMAIN is not set in ENV."
    end

    api_url = URI("https://api:#{API_KEY}@api.mailgun.net/v3/#{MAIL_DOMAIN}/messages")
    to_addr = [a.email, b.email].join(',')

    res = Net::HTTP.post_form(
      api_url,
      :from => "noreply@#{MAIL_DOMAIN}",
      :to => to_addr,
      :subject => "Recurser, you've been matched!",
      :text => email_body,
    )

    p to_addr
    p res
    p res.body
  end

  def email_body
    return <<-BODY

    Hello!

    You two should meet:

    #{a.name} - #{a.email}

    #{b.name} - #{b.email}

    This is an autogenerated email by https://meetrc.herokuapp.com. It is an opt-in way to meet fellow recursers. We heartily suggest you respond to this email and set up a time and place to hang out!

    <3
    Doorbot.

    BODY
  end
end
